root = "."
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/server"
cmd = "go build -o ./tmp/server ./cmd/server"
delay = 1000
exclude_dir = ["tmp", "logs"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "0s"
send_interrupt = false
stop_on_root = false

[log]
time = false
main_only = true

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
